spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  main:
    banner-mode: off

server:
  port: 6001

finefines:
  license-key: HX783-5PN1G-CRJ4A-K2L7V

vehicle-information.address: http://${VEHICLE_REGISTRATION_SERVICE:localhost}:6002/vehicleinfo/{licenseNumber}
# Used for service discovery when service-to-service invocation is used
vehicle-registration-service.name: ${VEHICLE_REGISTRATION_SERVICE:vehicleregistrationservice}